version: '3'

services:
  app-principal:
    build:
      context: .
    depends_on:
      - wiremock
    networks:
      - app-network
    environment:
      - WIREMOCK_URL=http://wiremock:8080  # A URL do WireMock
    ports:
      - "8081:8080"  # Expondo a porta 8080 da aplicação principal para o host

  wiremock:
    image: wiremock/wiremock:2.35.0
    networks:
      - app-network
    ports:
      - "8080:8080"  # Expondo a porta 8080 do WireMock para o host
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings  # Onde ficam as definições dos mapeamentos
      - ./wiremock/__files:/home/wiremock/__files  # Arquivos de resposta mockada

networks:
  app-network:
    driver: bridge
