version: '3'

services:
  wiremock:
    image: wiremock/wiremock:3.11.0
    networks:
      - app-network
    ports:
      - "8080:8080"  # Expondo a porta 8080 do WireMock para o host
    volumes:
      - ./wiremock/mappings:/home/wiremock/mappings  # Onde ficam as definições dos mapeamentos
    environment:
      JAVA_OPTS: -Dfile.encoding=UTF-8
    entrypoint: ["/docker-entrypoint.sh", "--global-response-templating", "--disable-gzip", ""]

  db:
    container_name: postgres-db
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  web:
    build:
      context: .
    depends_on:
      - wiremock
      - db
    networks:
      - app-network
    ports:
      - "8081:8081"

networks:
  app-network:
    driver: bridge
